47degrees/sbt-microsites

README.md, src/main/scala/microsites/FileHelper.scala, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala
This PR provides:
* Prerequisites section
* Recursive utility to copy all the resources under `/path/to/projectpath/src/main/resources/microsite` to `resource_managed/main/jekyll/img` folder (according to the original structure).
Please, @rafaparadela could you review? Thanks.
=> JP - Copy Image Resources Utility

README.md, src/main/scala/microsites/Layouts.scala, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositeSettings.scala, src/main/scala/microsites/MicrositesPlugin.scala
Please, @rafaparadela could you review? Thanks!
=> JP - Copying override css and Other improvements

README.md, build.sbt, docs/src/main/resources/css/override.css, project/plugins.sbt
This PR brings the basic structure to use the plugin to generate the microsite associated with this plugin (inception :) )
Please, @rafaparadela could you take a look? Thanks!
=> JP - Creates docs module

build.sbt, js/src/main/scala/kazari/KazariPlugin.scala, js/src/main/scala/kazari/model/EvaluatorConfig.scala, js/src/main/scala/kazari/model/EvaluatorRequest.scala
This PR introduces "Kazari", a Scala.JS-powered plugin that will allow developers to add Scala Exercises-like abilities to their documentations. Basically it will traverse the DOM of any site which includes the generated JS script, decorate any Scala code block by adding an "evaluate" button (which will send requests to our Scala remote evaluator) and also allow live code edition and evaluation.
Right now the plugin just decorates the code with a button to allow calls to the remote evaluator, sending basic requests to the remote evaluator. Refactoring of the network code is also needed, as now it's using JQuery simple Ajax calls. Plans to integrate the remote evaluator client are in motion!
This PR is partly dependant on scala-exercises/evaluator#31, which allows the Scala evaluator to …
=> Rough draft for Kazari JS plugin for code decoration

docs/src/main/tut/docs/customize.md
Instructions for relative links working in both Github md style navigation and generated Jekyll site.
@jdesiloniz @juanpedromoreno can you please review? Thanks.
=> Added instructions to have navigable Github + Jekyll docs

docs/src/main/tut/docs/settings.md, src/main/resources/js/main.js, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/sbt-test/microsites/config-hosting/README.md, src/sbt-test/microsites/config-hosting/build.sbt, src/sbt-test/microsites/config-hosting/project/plugins.sbt, src/sbt-test/microsites/config-hosting/test, src/test/scala/microsites/util/Arbitraries.scala
First run at #123. Note that I also upgraded FontAwesome to 4.7.0 only because it added a GitLab icon in 4.6.0.
=> Add abilitiy to configure different git hosting services.

README.md
Adds [hammock](http://pepegar.github.io/hammock) to the _sbt-microsites in the wild_ section.
=> add hammock as a user of sbt-microsites

.gitignore, build.sbt, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/layouts/PageLayout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/test/scala/microsites/util/Arbitraries.scala
Fixes: #114 
This PR adds code to let users customize a favicon in their microsites. It also divides the current MicrositeSettings case class in several case classes as we already reached the point of having more than 22 fields.
Could you please review, @juanpedromoreno? Thanks!
=> Support for favicon

build.sbt, src/main/scala/microsites/MicrositesPlugin.scala
Fixes: #134 
This PR fixes a bug that prevented non-PNG image resources to be used in microsites. `sbt-site` uses a filter setting to copy those files, but until now it wasn't being used correctly. The right configuration will be now applied by default, and will include the most common image file extensions.
Could you please review, @juanpedromoreno? Thanks!
=> Including default includeFilter in sbt-microsites settings

src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/PageLayout.scala
Remove inline styles preventing logo on docs and page layouts from being rendered at 2x.
To see this in action, uncheck the `background` inline style for the logo on these pages:
- Example for docs layout: http://typelevel.org/cats/typeclasses.html
- Example for page layout: http://typelevel.org/cats/colophon.html
and see how they now render using the 2x version on a high DPI (retina) screen.
=> Remove logo inline styles

build.sbt, docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/test/scala/microsites/util/Arbitraries.scala
Fixes: #136 
This PR adds a default option for the favicon setting in the `sbt-microsites`, that creates a set of favicons from the `navbar_brand2x.jpg` file (offering different sizes for different devices) and links them to our different layouts.
Could you please review, @juanpedromoreno? Thanks!!
=> Autogenerate favicons from the navbar_brand file as a default option

src/main/scala/microsites/MicrositesPlugin.scala
This PR adds CNAME files to the default includeFilters for the sbt-microsites settings. Could you please review, @raulraja @juanpedromoreno? Thanks!
=> Adding CNAME as default includeFilter in Jekyll

KAZARI_README.md, README.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/BuildHelper.scala, src/test/scala/microsites/util/Arbitraries.scala, version.sbt
This PR is related with issue #144 (currently, there is no need to send the compiler flags) and allows Kazari to include the right dependencies depending on the Scala version and the artefactId. 
It also increments the Kazari version to `0.6.0-SNAPSHOT`
@raulraja could you please review?
Thanks!
=> Add Scala Version to KazariDependency

.scalafmt, .scalafmt.conf, build.sbt, kazari/src/main/scala/kazari/KazariUIBehavior.scala, project/ProjectPlugin.scala, project/build.properties, project/plugins.sbt, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/layouts/MenuPartialLayout.scala, src/main/scala/microsites/layouts/PageLayout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/FileHelper.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/test/scala/microsites/util/Arbitraries.scala
* Upgrades sbt version
* Upgrades sbt-ghpages plugin version
* Moves the artifact to `com.47deg` groupId
Please, @fedefernandez could you review? Thanks!
=> Integrates sbt-org-policies Plugin

.travis.yml, README.md, docs/src/main/tut/docs/index.md, project/ProjectPlugin.scala, project/plugins.sbt, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/MicrositeHelper.scala, version.sbt
This PR fixes Kazari build bumping the `github4s` version through sbt-org-policies-plugin. It also will release a new minor version of sbt-microsites.
Please, @fedefernandez  could you review? Thanks!
CC @jdesiloniz
=> Fixes Kazari Build

docs/src/main/tut/docs/build-the-microsite.md, docs/src/main/tut/docs/publish-with-travis.md, docs/src/main/tut/docs/settings.md, docs/src/main/tut/index.md, project/ProjectPlugin.scala, project/plugins.sbt, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/util/MicrositeHelper.scala, version.sbt
This PR replaces the publishMicrosite task with a command. Now, depending of the `micrositePushSiteWith` setting value, the plugin will publish the site with sbt-ghpages or github4s API.
Please @juanpedromoreno, could you review? Thanks!
=> Use GitHub api to publish ghpages

docs/src/main/tut/docs/settings.md, project/ProjectPlugin.scala, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
Fixes #157 Add Google Analytics to microsite settings
=> Add Google Analytics settings

README.md, docs/src/main/tut/docs/index.md
Please, @fedefernandez have a look when you have a chance. Thanks.
=> Auto-update sbt-microsite version in doc files

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
=> Embed gitter channel

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
Add meta tag and doc for Twitter creator
Fix Twitter image meta tag for Twitter card
Add Twitter and homepage settings docs
Fixes #156 and #179
=> Fixes metatags and solarized-dark issues

project/ProjectPlugin.scala, project/plugins.sbt, src/main/scala/microsites/MicrositesPlugin.scala
This PR provides an enriched version of `includeFilter` setting scoped to both `makeSite` and `Jekyll`, where we are adding the ability to copy source and resource files with extension `yml`, `json` and `svg`.
=> Enriched version of `includeFilter`

project/ProjectPlugin.scala
@juanpedromoreno does `sbt-microsites` need these dependencies? I didn't notice any of them when I grep'ed the codebase and the CI build passes without them.
@tpolecat noticed https://gitter.im/47deg/sbt-microsites?at=5989f779bc46472974651d23
=> Remove unnecessary dependencies

project/ProjectPlugin.scala, project/plugins.sbt, version.sbt
https://github.com/47deg/sbt-org-policies/compare/v0.5.8...v0.5.14
https://github.com/47deg/sbt-microsites/compare/v0.6.1...bump-sbt-org-policies
=> Bump sbt org policies. Release 0.6.2

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/LayoutTest.scala, src/test/scala/microsites/util/Arbitraries.scala
Closes #218 
I'm not completely fond of `micrositeFooterText` as a setting key name because there are 2 lines in the footer. This setting only allows modifying the second the second line.
=> User configurable footer

version.sbt
Fixes https://github.com/47deg/sbt-microsites/issues/211
This PR releases a new version of `sbt-microsites` plugin, which it makes it compatible with `{1.0.x, 0.13.16}`.
This has been possible thanks to @suhasgaddam , who made the main work at  https://github.com/47deg/sbt-microsites/pull/221.
=> Releases 0.7.0 - Cross-built for sbt 0.13 and sbt 1.0

version.sbt
This new version will rely on tut 0.6.1. It was already fixed but not released.
See https://github.com/typelevel/cats/pull/1919 . This PR makes the new release.
=> Releases 0.7.1

project/plugins.sbt, src/main/scala/microsites/MicrositeKeys.scala, version.sbt
This PR solves the issue when publishing the microsite to GH pages. It releases a new patch version with this fix.
Fixes https://github.com/47deg/sbt-org-policies/issues/656
=> Fixes publishMicrosite dynamic task

project/ProjectPlugin.scala, project/plugins.sbt, version.sbt
=> Bump sbt-org-policies

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/sbt-test/microsites/change-default-paths/build.sbt, src/sbt-test/microsites/change-default-paths/src/main/resources/plugins/GitterTag.rb, src/sbt-test/microsites/change-default-paths/src/main/tut/docs.md, src/sbt-test/microsites/change-default-paths/test, src/test/scala/microsites/util/Arbitraries.scala
This PR adds support for custom Jekyll plugins, introducing a configurable `micrositePluginsDirectory` which defaults to `resources/microsite/plugins`.
This is essentially a port of https://github.com/scalacenter/scalafix/pull/386/commits/24c289c5aaf3842c3ffbd0a05c91c9ab8f64cf33, which turned out to be very useful for defining custom liquid tags.
=> Add support for custom Jekyll plugins

.travis.yml, project/ProjectPlugin.scala, project/build.properties, project/plugins.sbt, src/main/scala/microsites/util/MicrositeHelper.scala, version.sbt
This PR updates to tut version `0.6.2` through https://github.com/47deg/sbt-org-policies.
It releases a new patch version (`0.7.5`).
=> Updates tut 0.6.2

project/ProjectPlugin.scala, project/plugins.sbt, version.sbt
In the previous release, we missed bumping the tut version for sbt `0.13.x` (`0.5.6`).
This PR will release `0.7.6`, which will use the latest `tut` versions for both sbt `1.0.x` and `0.13.x`.
=> Updates missed tut 0.5.6 for sbt 0.13.x

src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/Layout.scala
This PR disables or enables kazari in `DocsLayout` and kazari's styles in `Layout`, depending of the `micrositeKazariEnabled` setting.
@jdesiloniz @juanpedromoreno  could you please review?
Thanks!
=> Disabling kazari in DocsLayout and kazari styles if kazari is not required

project/ProjectPlugin.scala, project/plugins.sbt, src/main/scala/microsites/layouts/Layout.scala
* Upgrade sbt-org-policies version dependencies to 0.8.17.
* Set async attribute for the GA script code, to not make the rest of
the HTML parsing get stopped by it.
* Position to load and parse the Google Analytics code after the rest of
the needed dependencies, specially after the CSS styling files, thus
making the render smoother between navigation jumps.
This fixes #75
=> Change GA script parsing mode for smoother navigation jumps

src/main/resources/_sass/_docs.scss, src/main/resources/js/main.js, version.sbt
* Add three JS function to main.js, which given a DOM content block, traverse its header elements, and given that they include an id attribute, an anchor link element will be added.
* As the project already uses Font Awesome, this link shows the fa-link icon.
* Add the necessary CSS code to get this added element hidden by default, and show it on hover.
This closes #74.
=> Add anchor links handlers

.travis.yml, docs/src/main/tut/docs/index.md, docs/src/main/tut/docs/publish-with-travis.md
As of 6 Dec 2017, Ruby 2.2.3 does not meet the gem constraint of build_dep 1.5.0 [1], a transitive dependency of jekyll 3.2.1. It's a temporary fix.
[1] https://travis-ci.org/tpolecat/doobie/jobs/312232582
=> Bump ruby version to 2.2.8 in docs

src/main/scala/microsites/MicrositeKeys.scala
I'm not sure exactly how `SettingKey.apply` changed such that these definitions result in "A named attribute key must start with a lowercase letter" errors on sbt 1.1.0-RC1, but using `settingKey` fixes the issue and is more consistent, anyway.
=> Use settingKey for SettingKey definitions

docs/src/main/tut/docs/settings.md, kazari/src/main/scala/kazari/KazariPlugin.scala, kazari/src/main/scala/kazari/KazariUIBehavior.scala, kazari/src/main/scala/kazari/codemirror/CodeMirrorHelper.scala, kazari/src/main/scala/kazari/domhelper/DOMHelper.scala, kazari/src/main/scala/kazari/domhelper/DOMTags.scala, project/plugins.sbt, src/main/scala-2.12/microsites/util/MicrositeHelperSpecific.scala, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/layouts/MenuPartialLayout.scala, src/main/scala/microsites/layouts/PageLayout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/BuildHelper.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/test/scala/microsites/DocsLayoutTest.scala, src/test/scala/microsites/HomeLayoutTest.scala, src/test/scala/microsites/LayoutTest.scala, src/test/scala/microsites/MenuPartialLayoutTest.scala, src/test/scala/microsites/PageLayoutTest.scala, src/test/scala/microsites/util/Arbitraries.scala, version.sbt
* Update sbt-org-policies dependency to 0.8.21
* Update copyright notice to 2018
* Add `micrositeStaticDirectory` feature, which by setting it will copy a directory without processing it in any way to the generated Jekyll directory
* Update documentation reflecting this new feature
* Release a new version, 0.7.14
This closes #250
=> Add micrositeStaticDirectory feature

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
- adds setting key `micrositeShareOnSocial` whether to show/hide the
share on social buttons in docs layout
- adds setting key `micrositeGithubLinks` whether to show/hide GitHub
links for stars and forks in docs layout
Please let me know whether you are fine with this addition or if I'm missing something. Also, naming and correct locations for the settings are up for discussion…
=> allows hide Github and Social links in `docs` layout

project/plugins.sbt, version.sbt
This PR solves #259.
I am bumping `sbt-org-policies` to `0.8.28`. This version has the latest version of `tut` required by @BennyHill.
=> Bumps sbt-org-policies version

project/ProjectPlugin.scala
Tut 0.6.4 adds a fix for https://github.com/tpolecat/tut/issues/65, which
makes sure that incomplete input does not pass compilation
=> Update tut to 0.6.4 for incomplete input fix

docs/src/main/tut/docs/layouts.md, docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
Fix #267!
Ping @calvellido Take a look when you have time.
Thanks again for the support. 
TODO:
=> #267 documentation label configurable

version.sbt
This new patch release (0.7.21) will use the new version of `tut`: 0.6.6, thanks to @xuwei-k
=> Release - Updating to tut 0.6.6

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/microsites.scala
I'm working with sbt-microsites on projects that are hosted on private Github instances. Currently the gitSiteUrl sets the URL to github.com if GitHub is the gitHostingService. This means I can't correctly link to my hosted Github repos with the default links in the template header, footer, and homepage. 
This pull request updated the gitSiteUrl to check the `gitHostingService` and `gitHostingUrl` attributes. If it is MicrositeKeys.GitHub and an empty string it returns the existing formatted URL, otherwise it returns the user set  `gitHostingUrl`.
=> gitSiteURL supports MicrositeKeys.GitHub and gitHostingUrl

docs/src/main/tut/docs/settings.md
The current documentation does not line up with https://github.com/47deg/sbt-microsites/blob/master/src/main/scala/microsites/MicrositesPlugin.scala#L75
=> Fix default layouts path

docs/src/main/tut/docs/settings.md, src/main/resources/_sass/_docs.scss, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
for #96 
I added a configuration setting named `micrositeEditButtonText`. By default it's set to None and the button is not visible. If it's set to Some with a string a button will appear at the bottom of pages with the DocsLayout. The button will have the text of the given string and link to the edit view of the page in the project repository.
For example for the page https://www.vinyldns.io/api/create-zone.html the button would link to https://github.com/VinylDNS/vinyldns/edit/master/modules/docs/src/main/tut/api/create-zone.md
Desktop view:
Mobile view.
=> add 'Edit Page' feature to doc pages

README.md
This PR improves the display of logos in the README by using the `navbar_brand.png` image of each site. This should provide a more consistent size for them and make the table better looking.
=> Improve logos in the README

src/main/scala/microsites/layouts/Layout.scala
I was wondering why img/poster.png was not shown on Twitter for my web page https://wvlet.org/airframe/, generated by sbt-microsites. 
twitter:image tag was pointing to the `img/poster.png`, not `(site.url)/(site.baseurl)/img/poster.png`
By using the same image path with `og:image` meta tag, we can fix this image link path.
=> Fix twitter image URL

docs/src/main/tut/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
#283 didn't truly fix the issue because Twitter requires absolute URLs for images.
This PR adds a new configuration `micrositeUrl` when we need to specify the site absolute url. 
**Alternative approaches:**
- Setting `site.url`. But if we set this value in _config.yml, it makes difficult to see local images updates because there are many templates using `{{site.url}}` (e.g., favicon URLs), so all icon images refer remote server URLs.
- Using a twitter-card specific configuration (e.g., micrositeTwitterCardImageAbsoluteUrl)
With this fix, the card validator https://cards-dev.twitter.com/validator of Twitter icon can properly show the card image (/image/poster.png):
=> Use the site absolute url for twitter:image

project/ProjectPlugin.scala
typelevel algebra wants a version that can build against scala 2.13.0-M5 (see typelevel/algebra#221)
=> upgrade tut to 0.6.9

.travis.yml, docs/src/main/tut/docs/index.md, docs/src/main/tut/docs/publish-with-travis.md, docs/src/main/tut/docs/settings.md
fix typo, and the following rubygems-update error incidentally:
https://travis-ci.org/47deg/sbt-microsites/jobs/469938515
https://travis-ci.org/47deg/sbt-microsites/jobs/469938514
=> fix typo with bumping ruby version to 2.3.0 in travis

project/ProjectPlugin.scala, project/plugins.sbt, version.sbt
Closes https://github.com/47deg/sbt-microsites/issues/256
Closes https://github.com/47deg/sbt-microsites/issues/213
Closes https://github.com/47deg/sbt-microsites/issues/214
Release **0.9.0-M1**
=> Upgrades the project by using the latest sbt-org-policies version

project/plugins.sbt, version.sbt
M1 is working as expected, so we are ready to release a new minor version of the library where the build is now fully upgraded.
**0.9.0** would be identical to **0.9.0-M1**.
=> Releases 0.9.0

docs/src/main/tut/docs/settings.md
follow up from https://github.com/vinyldns/vinyldns/pull/625
there's an `includeFilter in makeSite` configuration setting that determines what files are copied during the microsite build. Adding that information to the documentation.
=> add "includeFilter in makeSite" to docs

src/main/scala/microsites/layouts/DocsLayout.scala
This PR fixes #301
For this normalized to lower case variables are created to solve the comparasation.
=> Active doc page highlighted

version.sbt
Sett version to 0.9.1 triggering a new patch release including:
- #315 Update the latest Jekyll version
- #314 Active doc page highlighted
- #301 Code highlighted in the main page
=> Release version 0.9.2

README.md
Link and logo are broken + the project appears to no longer be using sbt-microsite 
> Remove sbt microsite and scoverage as no longer in use
https://github.com/zio/zio/commit/51ae75d1f1462193b1719067ce00e3ddd867644f
=> Remove ZIO from "microsites in the wild"

src/main/scala/microsites/layouts/DocsLayout.scala
* Consolidate two editButton href tags into one
This fixes #323
=> Consolidate two editButton href tags into one

version.sbt
Setting version to 0.9.4 triggering a new patch release including:
* #324 - Consolidate two `editButton` href tags into one
=> Release version 0.9.4

docs/src/main/tut/docs/settings.md
Without this change, the `{{page.path}}` blocks actually resolve on the published microsite (from https://47deg.github.io/sbt-microsites/docs/settings.html):
With the change it doesn't. Here's an example of what the results look like on my generated test site:
=> Add {% raw %} directive to embedded {{page.path}}

src/main/scala/microsites/MicrositeKeys.scala, src/sbt-test/microsites/mdoc-extra-md-files/CONSEQUAT.md, src/sbt-test/microsites/mdoc-extra-md-files/README.md, src/sbt-test/microsites/mdoc-extra-md-files/build.sbt, src/sbt-test/microsites/mdoc-extra-md-files/docs/index.md, src/sbt-test/microsites/mdoc-extra-md-files/project/plugins.sbt, src/sbt-test/microsites/mdoc-extra-md-files/test
This PR fixes #318 partially.
_Tut_ includes a very [convenient method](https://github.com/tpolecat/tut/blob/series%2F0.6.x/modules/plugin/src/main/scala/tut/TutPlugin.scala#L144) to compile a single markdown file, so the extra MD files are properly compiled and moved to Jekyll.
But in the case of _Mdoc_, currently it not including this feature, so at the moment, the solution I'm proposing in this PR is just moving the MD files to Jekyll (but the Mdoc areas are not compiled).
Maybe in the next iteration, we should swap the order of the syntax compiling, in order to move the extra MD files to the input directory, then compile them, and finally move them to the Jekyll folder.
=> Supporting ExtraMDFiles with Mdoc

src/main/scala/microsites/MicrositesPlugin.scala
This fixes an issue in sbt-microsites where mdoc would always look for sources in a `docs` folder at the root of the sbt build, instead of a looking for it in the module's base directory.
=> Use project scope for mdoc sources setting, not ThisBuild

docs/docs/docs/build-the-microsite.md, docs/docs/docs/customize.md, docs/docs/docs/getting-start.md, docs/docs/docs/intro.md, docs/docs/docs/layouts.md, docs/docs/docs/publish-with-travis.md, docs/docs/docs/settings.md, docs/docs/docs/typechecked-snippets.md, docs/docs/index.md, docs/src/main/resources/microsite/data/menu.yml
This PR changes the site home layout to homeFeatures
=> Site home change

docs/docs/docs/build-the-microsite.md, docs/docs/docs/customize.md, docs/docs/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/sbt-test/microsites/config-yml/build.sbt, src/sbt-test/microsites/mdoc-compile/test, src/sbt-test/microsites/mdoc-extra-md-files/test, src/sbt-test/microsites/microsites-config-keys/build.sbt, src/sbt-test/microsites/microsites-tasks/test, src/sbt-test/microsites/tut-compile/test, src/test/scala/microsites/util/Arbitraries.scala
* Add `micrositeSassDirectory` setting.
* Add specific tasks to copy and process the SCSS and their partial files.
* Add specific _sass_ custom load path to Jekyll config.
* Remove config file copy, which breaks things when serving built sites.
* Add Sass/SCSS feature support documentation.
This closes #372
=> Custom Sass/SCSS support

version.sbt
- Update `sbt` version in Travis, micrositeDocumentationUrl #383
- Update `scalatest` to 3.1.0 #381
- Update `scalactic` to 3.1.0 #380
- Multiversion support #379
- Update `sbt` to 1.3.4 #378 
- Changes micrositeExtraMdFilesOutput default folder #377
- Custom Sass/SCSS support #373
- Update `sbt-mdoc` to 2.0.2 #371
- Set homepage setting to be GitHub repo URL explicitely for the project #370 
- Site home change #368
- Streamline web 3rd party dependencies #367
- Modify `sbt-microsites` documentation folder #365
- Features layout section implementation #364
- Adds Java property `java.awt.headless=true` #363
- `mdoc` by default #362
- Use project scope for `mdoc` sources setting, not ThisBuild #357 by @pdalpra
- New style redesign #354
=> Release version 1.0.0

.travis.yml, docs/docs/docs/build-the-microsite.md, docs/docs/docs/customize.md, docs/docs/docs/getting-started.md, docs/docs/docs/layouts.md, docs/docs/docs/publish-with-travis.md, docs/docs/docs/settings.md
This PR: 
* Simplifies Travis docs deployment by using only the necessary commands.
* Reflects that simplification in some parts of the documentation.
* It also adds language tags to all code snippets in the documentation.
=> Simplify deployment - Improve docs

README.md
During the major upgrade of sbt-microsite to 1.x, which introduced mdoc, we've tested several configurations that worked for our site. Then, we decided to switch to using mdoc and Docusaurus to fully customize our web site as we wish: https://wvlet.org/airframe/
I'd like to thank you for developing this plugin. sbt-microsite has worked for us for years. As the number of documentation pages and the volume increase, our doc site is no longer at a micro-scale, so the time has come for us to graduate from sbt-microsite.
Thank you for the wonderful plugin. We've learned a lot about how we should organize our documentation by following the standards provided by sbt-microsite.
=> Airframe has graduated from sbt-microsite

docs/docs/docs/layouts.md, docs/docs/index.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/FeaturesLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/layouts/MenuPartialLayout.scala, src/main/scala/microsites/layouts/PageLayout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/BuildHelper.scala, src/main/scala/microsites/util/MicrositeHelper.scala
=> Implement feature links

.travis.yml
I feel like this could be the culprit as to why the current 1.1.1 version has not been published, but I'm not totally sure, as some parts of the workflow has been completed but others don't:
https://repo1.maven.org/maven2/com/47deg/sbt-microsites_2.12_1.0/
:thinking:
=> Remove hardcoded sbt version from Travis config

src/main/scala/microsites/util/MicrositeHelper.scala, src/test/scala/microsites/DocsLayoutTest.scala, src/test/scala/microsites/HomeLayoutTest.scala, src/test/scala/microsites/LayoutTest.scala, src/test/scala/microsites/MenuPartialLayoutTest.scala, src/test/scala/microsites/PageLayoutTest.scala, src/test/scala/microsites/util/Arbitraries.scala
* Add a proper doctype declaration `<!DOCTYPE html>` to all layouts when they are generated thought the render method of their TypedTag.
* Update some copyright notices.
This closes #427
=> Declare proper doctype on layouts

docs/docs/docs/build-the-microsite.md, docs/docs/docs/settings.md, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala
Most of the projects using this plugin use either Travis, Github Actions or other similar CIs. All these have in common that they set a git remote `origin` pointing to the original repository. We can extract that information from git to pre-populate the `micrositeGithubOwner` and `micrositeGithubRepo`.
Populate by default the `micrositeGithubOwner` and `micrositeGithubRepo` with the information extracted from calling `git ls-remote --get-url origin`.
=> Populate github owner/repo keys with default values from git remote

src/main/resources/_sass/light-style/_features.scss
After https://github.com/47deg/sbt-microsites/pull/430 we lost the main image in the features layout, as the proper `doctype` makes that `background-image` needing another way of setting its height. 
This PR fixes that.
=> Set absolute position to main features img relative to parent container

project/ProjectPlugin.scala, project/plugins.sbt, src/main/scala/microsites/MicrositeKeys.scala
* Adds `cats-effect` as a dependency.
* Updates `sbt-org-policies` to `0.13.2` properly.
* Uses IO data type when committing a directory.
=> Use cats-effect IO data type

src/main/resources/_sass/_bootstrap_override.scss
Despite the documentation saying that there isn't a size requirement for jumbotron patterns, it gets squished down to a fixed size on high density displays. This seems unintentional.
Fix it by changing the fixed size values to `auto`, which just uses the image size.
Bug in action on https://typelevel.org/cats:
Fixed:
=> Fix distorted 2x jumbotron pattern

README.md, build.sbt
The gitter link on the microsite and README is broken. This sets both to the proper values. There must have been some org change where this broke and it went unnoticed for a little while.
=> Fix Gitter links in README and microsite

build.sbt, project/dependencies.sbt, src/main/scala/microsites/ioops/FileWriter.scala, src/main/scala/microsites/util/MicrositeHelper.scala
Scrimage, a dependency of sbt-microsites, has actually been significantly out of date for some time, probably due to a dependency name change from `scrimage-core` to `scrimage-scala` for the Scala-specific dependencies. This updates the library, and replaces the one usage of it using the latest syntax.
EDIT: The scope of this has expanded slightly to also fixing the build, by rewriting the `copyJARResourcesTo` function (now `copyResourcesFromFileSystem`) to work with arbitrary filesystems. While I'm not entirely sure what the cause of the build issues was, this issue might have had something to do with the specific JDK I am using (adoptopenjdk 8) as the issue was nonexistent before, and only popped up recently in the build.
=> Update scrimage to 4.x from 2.x & fix copying resources

microsite/docs/docs/intro.md, microsite/docs/docs/settings.md, src/main/resources/_sass/light-style/_doc-search.scss, src/main/resources/_sass/light-style/_light-docs.scss, src/main/resources/css/light-style.scss, src/main/resources/js/search.js, src/main/resources/js/version-selector.js, src/main/resources/lunr/LICENSE, src/main/resources/lunr/lunr.js, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/FeaturesLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/layouts/PageLayout.scala, src/main/scala/microsites/microsites.scala, src/main/scala/microsites/util/MicrositeHelper.scala, src/test/scala/microsites/util/Arbitraries.scala
Resolves #503 and #196.
Depends on #529 (please review that first)
Adds a basic search functionality, client-side and enabled by default, to sbt-microsites. Currently the search only provides links to documents, and not headings within each document. Doing that would require a bit more effort, and I believe this is a good stop-gap solution for search that at least gets our foot in the door.
There is a search bar at the top of the home page and all document pages. Typing terms in the search (according to https://lunrjs.com/ rules) will generate a score, and use this to search relevant results. The user can press the up and down arrow keys to navigate the list, or ESC to close the drop-down.
Basic demo of search, nav, and ESC to close: …
=> Add Document Search

build.sbt
Supersedes #499.
ScalaCheck updated to 1.15 a while back, and this transitively brings that in along with the latest scalatest version so we're not stuck on an old version of both.
=> Update ScalaCheck to 1.15, scalatestplus scalacheck to 3.2.3.0

microsite/docs/docs/settings.md, src/main/resources/_sass/light-style/_features.scss, src/main/resources/_sass/light-style/_masthead.scss, src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/MicrositesPlugin.scala, src/main/scala/microsites/layouts/FeaturesLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala, src/main/scala/microsites/microsites.scala, src/test/scala/microsites/util/Arbitraries.scala
Resolves #508
Adds a config option for specifying where you would like the big call-to-action button on the front page to link to, between your `repo` or your `docs` page.
Simply set `micrositeHomeButtonTarget := "docs"` and you will get a button that looks like this:
and redirects to your documents URL, assuming it is defined.
=> Allow config to specify if home-page button goes to repo or docs

src/main/resources/_sass/_doc-search.scss, src/main/resources/_sass/_docs.scss, src/main/resources/_sass/_home.scss, src/main/resources/css/light-style.scss, src/main/resources/css/pattern-style.scss, src/main/resources/js/main.js, src/main/scala/microsites/layouts/DocsLayout.scala, src/main/scala/microsites/layouts/HomeLayout.scala, src/main/scala/microsites/layouts/Layout.scala
Resolves #542 
Enables search for the pattern theme! A lot of older microsites are still using this theme so it's good that search is available to it. I had some difficulty meshing the style of the light theme with the pattern theme, and it might look a bit visually inconsistent in some small areas, but I feel this is at least a good start.
Also removes the Google+ share-on-social link, as that service has been discontinued for some time. It also made it easier to adjust the CSS with it gone as there was more room to play with.
Pic examples of the search in pattern theme:
I made sure that the CSS changes here didn't override any previous visual settings, so the rest of the navbar links still have transparency on hover, docs navbar entries are still uppercase without affecting search …
=> Enable Search for Pattern Theme

build.sbt, project/dependencies.sbt, src/main/scala/microsites/util/MicrositeHelper.scala
Resolves #535 
Scrimage now allows you to pass in a classloader, so we don't need to override the one the plugin uses by default.
=> Remove Scrimage classloader hack

build.sbt, project/dependencies.sbt, src/main/scala/microsites/github/GitHubOps.scala
This restores the changes made in b9bbd817bef7790a3c00f74cbbf7822dd15fd6b0 regarding base64 encoding. Tested locally and it seems to work now (see https://github.com/47degrees/sbt-microsites/commit/d3c35c279115489c528c23f66d76a80c0f9cb332)
Related to #727
=> Restores old encoding

src/main/scala/microsites/MicrositeKeys.scala, src/main/scala/microsites/github/GitHubOps.scala, src/test/scala/microsites/MicrositeAutoImportSettingsTest.scala, src/test/scala/microsites/util/Arbitraries.scala
When `gitHostingURL` is set, we see the following error:
```
Error making request to GitHub
| => bat microsites.github.GitHubOps.$anonfun$run$1(GitHubOps.scala:208)
at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
at flatMap @ org.http4s.client.PoolManager.releaseRecyclable(PoolManager.scala:225)
at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
at unsafeRunSync @ microsites.MicrositeAutoImportSettings.$anonfun$micrositeTasksSettings$14(MicrositeKeys.scala:496)
at withPermit @ org.http4s.client.PoolManager.shutdown(PoolManager.scala:370)
at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
at …
```
=> Fix UnauthorizedError on GitHub Enterprise publish
