47degrees/sbt-microsites

- src/main/resources/_sass/_colors.scss
- src/main/resources/_sass/_home.scss
- src/main/scala/microsites/Layouts.scala
> Fix general styles

- README.md
- src/main/scala/microsites/FileHelper.scala
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositeSettings.scala
- src/main/scala/microsites/MicrositesPlugin.scala
Please, @rafaparadela could you review? Thanks.
> JP - Adds new settings to include extra Markdown File

- src/main/resources/_sass/_bootstrap_override.scss
- src/main/resources/_sass/_colors.scss
- src/main/resources/_sass/_variables_style.scss
- src/main/scala/microsites/Layouts.scala
> Change header menu

- README.md
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositeSettings.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/layouts/HomeLayout.scala
Please, @rafaparadela Could you review? Thanks!
> Brings new setting for site base url

- README.md
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositeSettings.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/layouts/HomeLayout.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/layouts/PageLayout.scala
Please, @rafaparadela could you review? Thanks!
> Configurable Documentation URL

- src/main/resources/_sass/_home.scss
- src/main/scala/microsites/layouts/DocsLayout.scala
- src/main/scala/microsites/layouts/HomeLayout.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/layouts/MenuPartialLayout.scala
- src/main/scala/microsites/layouts/PageLayout.scala
Please, @rafaparadela have a look. Thanks.
> Fixes Relative Paths pointing to Resources

- README.md
- build.sbt
- version.sbt
Please, @fedefernandez could you review it? Thanks!
> Bumps initial release version

- build.sbt
- project/plugins.sbt
Please, @israelperezglez could you review? Thanks!
> No publish settings for docs sbt module

- src/main/scala/microsites/util/MicrositeHelper.scala
Please, @israelperezglez could you review? Thanks!
> Copies IMG folder togeteher with js and css folders

- .travis.yml
- build.sbt
- project/plugins.sbt
- src/sbt-test/microsites/basic/build.sbt
- src/sbt-test/microsites/basic/project/plugins.sbt
- src/sbt-test/microsites/basic/test
- version.sbt
> JP - Adds Scripted Plugin

- .travis.yml
I need to merge this one to test if it works for master and Travis now.
> Removing wrong if branch

- README.md
- version.sbt
Please, review at your convenience. Thanks!
> Releases new Plugin Version

- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/util/FileHelper.scala
Fixes https://github.com/47deg/sbt-microsites/issues/48
Please, @jdesiloniz could you review? Thanks!
> Filter files by extension in the css case

- src/main/resources/_sass/_bootstrap_override.scss
À la GitHub.
It slightly improves how tables are styled. I'm no web designer, so
bear with me with my poor CSS style.
> Fix #76: Improve table style

- README.md
@justinelsberry @MaureenElsberry Can you please review?
I'll wait for some of the cats folks to give the go ahead before merging this.
> Adds usage in the wild and includes cats as first lib

- README.md
This PR adds Typelevel Scala to the Wild Section (issue https://github.com/47deg/sbt-microsites/issues/91)
@raulraja @jdesiloniz 
Please, have a look. Thanks.
> Adds Scala Fork to wild section

- README.md
- docs/src/main/tut/docs/index.md
- project/plugins.sbt
This PR bumps our docs to `0.3.2` version.
Please, @raulraja @jdesiloniz  could you take a look? Thanks!
> Bumps version in doc files to 0.3.2

- docs/src/main/tut/docs/settings.md
This PR includes a fix for a small issue causing a build error in the documentation files. Could you please review, @juanpedromoreno? Thanks!
> Fix issue in documentation

- README.md
- docs/src/main/tut/docs/index.md
- notes/0.3.3.markdown
- project/plugins.sbt
Please, @jdesiloniz @raulraja could you review? Thanks!
> Adds changelog notes and Updates docs

- README.md
@raulraja @juanpedromoreno @rafaparadela Would one of you be able to review this please?
Thanks!
> Add scalacheck-datetime to the "In the wild" section

- README.md
Thanks for a wonderful project!
> Add Algebird to "in the wild" section

- README.md
> Add Scalding to "In the Wild" section

- README.md
https://github.com/julien-truffaut/Monocle/commit/ad5fdcccae1954c94f66b6516a4ee0aff02b9f37#diff-5a1653031ce4960aa9c117b3960708c2
/cc @julien-truffaut
> fix monocle logo url

- README.md
Fixes https://github.com/47deg/sbt-microsites/issues/91
Please, @dialelo @rafaparadela could you take a look? Thanks!
> Adds fetch and github4s to the in the wild section

- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/domain/MicrositeSettings.scala
- src/main/scala/microsites/util/MicrositeHelper.scala
- src/sbt-test/microsites/change-default-paths/build.sbt
- src/sbt-test/microsites/extra-md-files/CONSEQUAT.md
- src/sbt-test/microsites/extra-md-files/README.md
- src/sbt-test/microsites/extra-md-files/build.sbt
- src/sbt-test/microsites/extra-md-files/project/plugins.sbt
- src/sbt-test/microsites/extra-md-files/test
- src/sbt-test/microsites/microsites-config-keys/build.sbt
- src/sbt-test/microsites/scala-2-12/build.sbt
- src/sbt-test/microsites/tut-compile/build.sbt
- src/test/scala/microsites/util/Arbitraries.scala
Fixes https://github.com/47deg/sbt-microsites/issues/73
Please, @jdesiloniz could you take a look? Thanks!
> SBTM-73 Sync files outside from tut

- README.md
- docs/src/main/tut/docs/index.md
- notes/0.4.0.markdown
- project/plugins.sbt
Please, @jdesiloniz @fedefernandez  could you take a look? Thanks!
> Bumps Version

- docs/src/main/tut/docs/index.md
- docs/src/main/tut/docs/settings.md
Please, @MaureenElsberry could you review this PR? Thanks!
> Update Docs for 0.4.0 version

- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/docs/publish-with-travis.md
This PR closes #98 for adding documentation to publish microsite with Travis
@MaureenElsberry could you please review the language?
@juanpedromoreno thoughts?
> Documentation about publishing Microsite with Travis

- README.md
Fixed the broken image and links following the update from scalacheck-datetime to scalacheck-toolbox.
@juanpedromoreno would you be able to review please?
> Update entry for scalacheck-datetime to scalacheck-toolbox

- .travis.yml
Please, @fedefernandez could you review? Thanks!
> Allows to publish locally before run scripted tests

- src/main/scala/microsites/MicrositesPlugin.scala
Please, @fedefernandez have a look when you have a chance.
Thanks.
> Adds the sbt GhpagesPlugin as Requirement

- scripts/deploy.sh
Please, @fedefernandez have a look, thanks!
> Replaces publishSnaphot by publishSigned

- project/ProjectPlugin.scala
- project/plugins.sbt
Please, @fedefernandez could you review? Thanks!
> Org policies plugin and dep released versions

- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/layouts/DocsLayout.scala
- src/main/scala/microsites/layouts/HomeLayout.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/layouts/MenuPartialLayout.scala
- src/main/scala/microsites/layouts/PageLayout.scala
- src/main/scala/microsites/microsites.scala
- src/main/scala/microsites/util/BuildHelper.scala
- src/main/scala/microsites/util/MicrositeHelper.scala
Fixes #115  "Website built with Sbt-microsites - © 2016 47 Degrees"
> Add new line to the footer

- .travis.yml
- build.sbt
- kazari/src/main/scala/kazari/KazariPlugin.scala
- kazari/src/main/scala/kazari/KazariUIBehavior.scala
- kazari/src/main/scala/kazari/codemirror/CodeMirrorHelper.scala
- kazari/src/main/scala/kazari/domhelper/DOMHelper.scala
- kazari/src/main/scala/kazari/domhelper/DOMTags.scala
- project/ProjectPlugin.scala
- project/plugins.sbt
- scripts/deploy.sh
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/layouts/DocsLayout.scala
- src/main/scala/microsites/layouts/HomeLayout.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/layouts/MenuPartialLayout.scala
- src/main/scala/microsites/layouts/PageLayout.scala
- src/main/scala/microsites/microsites.scala
- src/main/scala/microsites/util/BuildHelper.scala
- src/main/scala/microsites/util/MicrositeHelper.scala
- src/test/scala/microsites/DocsLayoutTest.scala
- src/test/scala/microsites/HomeLayoutTest.scala
- src/test/scala/microsites/LayoutTest.scala
- src/test/scala/microsites/MenuPartialLayoutTest.scala
- src/test/scala/microsites/PageLayoutTest.scala
- src/test/scala/microsites/util/Arbitraries.scala
Please, @fedefernandez could you take a look? Thanks!
> Upgrades sbt-org-policies and its configuration

- docs/src/main/tut/docs/settings.md
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/microsites.scala
- src/test/scala/microsites/util/Arbitraries.scala
Added new val in the footer area to link to the organisation home page.
Fixes Issue #161
> Add new val "micrositeOrganisationHomepage" 

- README.md
- docs/src/main/tut/docs/index.md
- project/ProjectPlugin.scala
- project/plugins.sbt
- version.sbt
Please, @fedefernandez have a look. Thanks.
> Releases 0.5.2

- .travis.yml
- README.md
- build.sbt
Please @juanpedromoreno, could you review? Thanks
> Fixes artifact publish

- .travis.yml
- project/ProjectPlugin.scala
- project/build.properties
- project/plugins.sbt
- src/main/scala/microsites/layouts/Layout.scala
- version.sbt
Please @juanpedromoreno could you revieW? Thanks
> Upgrades sbt-org-policies and uses new method signature for fetching files

- src/main/scala/microsites/MicrositeKeys.scala
- version.sbt
Please, @fedefernandez could you review? Thanks!
> Adds task wrapper for the publishMicrosite Command

- CHANGELOG.md
Please @juanpedromoreno could you review? Thanks
> Update CHANGELOG.md with 0.5.7 release

- project/ProjectPlugin.scala
- project/plugins.sbt
This PR brings some fixes and enhancements through the plugin. 
Please, @fedefernandez , take a look. Thanks.
> Bumps sbt-org-policies version

- README.md
Fixed #193 - Added freestyle and libra to the list of usage in the wild
> Added Freestyle and Libra

- docs/src/main/resources/microsite/css/override.css
- src/main/resources/_sass/_home.scss
@calvellido   could you review this PR please?
fixed #152
> Review css jumbotron_pattern retina

- .travis.yml
- build.sbt
- project/ProjectPlugin.scala
- project/buildinfo.sbt
- project/plugins.sbt
This PR fixes the issue related to sbt scripted. Potentially, replaces https://github.com/47deg/sbt-microsites/pull/223.
> Bumps sbt-org-policies version in order to fix scripted issues

- project/plugins.sbt
- version.sbt
This PR will release `sbt-microsites` 0.7.4 once it's merged, including #231 .
> Releases 0.7.4 with #231

- .travis.yml
I updated the SBT version but not the filter 😞  
We should add support for this in sbt-org-policies ([#781](https://github.com/47deg/sbt-org-policies/issues/781)).
> Fixes travis release filter

- project/ProjectPlugin.scala
- project/plugins.sbt
- version.sbt
It updates dependency versions for org-policies and github4s, releasing
a new sbt-microsite version.
> Bump-ups versions

- src/main/scala/microsites/layouts/Layout.scala
> Add page title

- project/ProjectPlugin.scala
- project/plugins.sbt
- version.sbt
Released 0.7.19 version and updated sbt-org-policies to 0.9.2
> Release sbt-microsites v0.7.19

- version.sbt
This new version includes:
* #272 by @britneywright 
* #274 by @NeQuissimus
> Releases sbt-microsites 0.7.22

- docs/src/main/tut/docs/settings.md
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/microsites.scala
- src/sbt-test/microsites/microsites-config-keys/build.sbt
- src/test/scala/microsites/util/Arbitraries.scala
> Add support for additional highlighted languages

- version.sbt
> Release sbt-microsites 0.7.24

- README.md
Finch icon is white, it wasn't visible against the white background so I switched with Scalding.
> Changed position of Finch on README in order to see icon

- version.sbt
* Including small fixes and documentation updates.
> Release 0.7.25

- version.sbt
> Release with tut 0.6.9

- src/main/scala/microsites/layouts/HomeLayout.scala
- src/main/scala/microsites/layouts/Layout.scala
- use gitHostingService.name instead of implicit toString conversion
> Fix issue #229

- .travis.yml
- project/plugins.sbt
* Upgrade sbt-org-policies to 0.11.3, and by that apply the Scala Code of Conduct to the project
> Upgrade sbt-org-policies 0.11.3 applying Scala CoC

- version.sbt
Sett version to 0.9.1 triggering a new patch release including:
* #307 - add "includeFilter in makeSite" to docs
* #308 - Upgrade sbt-org-policies 0.11.3 applying Scala CoC
After this, I'll be updating project's own microsite and dependencies to use latest version.
> Release version 0.9.1

- src/main/scala/microsites/layouts/Layout.scala
This PR fixes #310 
Adds cloudflare highlight scripts in the main footer
> Home layout HighLighting

- .travis.yml
- docs/src/main/tut/docs/index.md
- docs/src/main/tut/docs/publish-with-travis.md
> Update to the latest stable Jekyll version

- .gitignore
- .travis.yml
- project/ProjectPlugin.scala
- project/plugins.sbt
This PR upgrades some of the sbt-microsite dependencies, including `mdoc` and `tut`.
> Build Upgrade

- README.md
I added Mocked Streams, which is widely used in the Kafka Streams + Scala ecosystem for unit-testing stream processing topologies. Please let me know if you have questions. 
Thank you!
> Added Mocked Streams library to list of projects using sbt-microsites

- docs/src/main/tut/docs/settings.md
- src/main/scala/microsites/layouts/Layout.scala
* Add rel attribute to external links to avoid security problems 
*  Fix library name on footer
* Update copyright
> Add rel attribute to external links to avoid security problems

- docs/src/main/tut/docs/index.md
* Update prerequisites versions in the documentation
> Update prerequisites versions doc info

- version.sbt
> Release version 0.9.5

- version.sbt
> Release version 0.9.6

- version.sbt
...  with the new tut version (0.6.13), among other updates.
> Releases 0.9.7

- src/main/scala/microsites/MicrositesPlugin.scala
Fixes https://github.com/47deg/sbt-microsites/issues/208
> Adds java property java.awt.headless=true

- project/ProjectPlugin.scala
* Set homepage setting to be GitHub repo URL explicitely for the project
This closes #369
> Set homepage setting to be GitHub repo URL explicitely for the project

- docs/docs/docs/customize.md
> Fix docs typo

- docs/docs/docs/settings.md
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
> Changes micrositeExtraMdFilesOutput default folder

- .travis.yml
- docs/docs/docs/getting-started.md
- project/ProjectPlugin.scala
* Set `micrositeDocumentationUrl` to be relative to site instead of absolute
* Update `sbt` version in Travis config and docs to 1.3.4
> Update sbt version in Travis, micrositeDocumentationUrl

- version.sbt
Huge thanks to @calvellido, @AntonioMateoGomez and everyone else for making this possible :)
> Release 1.0.0

- version.sbt
Reverts 47deg/sbt-microsites#382
> Revert "Release 1.0.0"

- src/main/resources/_sass/light-style/_features.scss
- src/main/resources/_sass/light-style/_light-docs.scss
- src/main/resources/_sass/light-style/_main.scss
- src/main/resources/_sass/light-style/_masthead.scss
- src/main/resources/_sass/light-style/_navbar.scss
This PR fixes some style issues in safari browser.
> Fixes safari styles

- version.sbt
- `publishMultiversionMicrosite` and fix `GHPagesPlugin` publishing #388 
- Update `sbt-mdoc` to 2.0.3 #387
- Fixes Safari styling #386
> Release version 1.0.1

- src/main/scala/microsites/MicrositeKeys.scala
> Make pushMicrosite a dynamic task and always return a task on it

- version.sbt
* Fix `pushMicrosite` by setting it as a dynamic task and always return a proper task on it #392
> Release version 1.0.2

- docs/docs/docs/troubleshooting.md
- docs/src/main/resources/microsite/data/menu.yml
> Add a troubleshooting page

- project/ProjectPlugin.scala
* Update transitive offered `mdoc` version to same in dependencies
> Update transitive offered mdoc to same in deps

- version.sbt
* Trigger the release of new minor version (1.1.0)
> Trigger new minor version (1.1.0)

- version.sbt
Apart from @scala-steward updates, this new version includes #417 .
> Release 1.1.1

- version.sbt
* Setting version to 1.1.2-SNAPSHOT
> Setting version to 1.1.2-SNAPSHOT

- version.sbt
* Trigger the release of new patch version (1.1.2)
> Trigger new patch version (1.1.2)

- .github/CODEOWNERS
- .gitignore
- .travis.yml
- CONTRIBUTING.md
- README.md
- docs/docs/docs/publish-with-travis.md
- project/ProjectPlugin.scala
- src/main/scala/microsites/layouts/Layout.scala
It also bumps the Scala version to the latest 2.12.x.
> Migrates from 47deg to 47degrees GH organization

- src/main/scala/microsites/Exceptions.scala
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/main/scala/microsites/github/Config.scala
- src/main/scala/microsites/github/GitHubOps.scala
- src/main/scala/microsites/ioops/FileReader.scala
- src/main/scala/microsites/ioops/FileWriter.scala
- src/main/scala/microsites/ioops/IOUtils.scala
- src/main/scala/microsites/ioops/ioops.scala
- src/main/scala/microsites/layouts/DocsLayout.scala
- src/main/scala/microsites/layouts/FeaturesLayout.scala
- src/main/scala/microsites/layouts/HomeLayout.scala
- src/main/scala/microsites/layouts/Layout.scala
- src/main/scala/microsites/layouts/MenuPartialLayout.scala
- src/main/scala/microsites/layouts/PageLayout.scala
- src/main/scala/microsites/microsites.scala
- src/main/scala/microsites/util/BuildHelper.scala
- src/main/scala/microsites/util/MicrositeHelper.scala
- src/main/scala/microsites/util/YamlFormats.scala
- src/test/scala/microsites/DocsLayoutTest.scala
- src/test/scala/microsites/HomeLayoutTest.scala
- src/test/scala/microsites/LayoutTest.scala
- src/test/scala/microsites/MenuPartialLayoutTest.scala
- src/test/scala/microsites/PageLayoutTest.scala
- src/test/scala/microsites/util/Arbitraries.scala
Update documentation and other files with latest changes.
> Update documentation and other files

- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/github/GitHubOps.scala
This PR bumps up:
* Github4s (adapting the code to the new release).
* Scalatags.
* Scalafmt.
Closes #474 
Closes #471 
Closes #470
> Upgrade Build

- README.md
(Seems like it used to be updated automatically by CI. Seems like something changed?)
> Readme to v1.2.1

- build.sbt
- microsite/docs/docs/settings.md
- src/main/scala/microsites/MicrositeKeys.scala
- src/main/scala/microsites/MicrositesPlugin.scala
- src/sbt-test/microsites/change-default-paths/build.sbt
- src/sbt-test/microsites/config-hosting/build.sbt
- src/sbt-test/microsites/config-yml/build.sbt
- src/sbt-test/microsites/mdoc-extra-md-files/build.sbt
- src/sbt-test/microsites/microsites-config-keys/build.sbt
Additionally, I'm updating the project to the latest version of github4s.
> Replaces deprecated SBT syntax
